# Deployment manifest for Harness
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-cv-prom-example-deployment
spec:
  selector:
    matchLabels:
      app: harness-cv-prom-example
  replicas: 1 
  template:
    metadata:
      labels:
        app: harness-cv-prom-example
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: harness-cv-prom-example
          image: {{.Values.image}}
          imagePullPolicy: Always
          command:
            - "java -jar /app/cv-example-app-1.0.0.jar"
          ports:
            - containerPort: 8082
