# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cv-example-app-service
spec:
  selector:
    app: cv-example-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080 
      nodePort: 30080 
  type: NodePort
